import { Product } from "@/types/product";

export const products: Product[] = [
    // Electronics
    {
        id: 1,
        title: "Wireless Noise-Canceling Headphones",
        price: 299.99,
        description: "Immersive sound with industry-leading noise cancellation. 30-hour battery life.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.9, count: 530 },
        brand: "AudioPro",
    },
    {
        id: 2,
        title: "Smart Home Speaker",
        price: 89.99,
        description: "Voice-controlled assistant with room-filling sound and smart home integration.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1589492477829-5e65395b66cc?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.5, count: 180 },
        brand: "TechHome",
    },
    {
        id: 3,
        title: "Professional Mechanical Keyboard",
        price: 159.00,
        description: "Tactile mechanical switches for ultimate typing precision and speed.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.9, count: 600 },
        brand: "KeyMaster",
    },
    {
        id: 4,
        title: "4K Ultra HD Monitor",
        price: 349.50,
        description: "Crystal clear display tailored for creative professionals and gamers.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.7, count: 120 },
        brand: "VisionTech",
    },
    {
        id: 5,
        title: "Smartphone Gimbal Stabilizer",
        price: 129.00,
        description: "Capture cinematic smooth video with your smartphone using this 3-axis gimbal.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1585802340331-b88307db1855?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.4, count: 85 },
        brand: "SteadyShot",
    },

    // Men's Clothing
    {
        id: 6,
        title: "Classic Denim Jacket",
        price: 110.00,
        description: "Vintage wash denim jacket. Timeless style that improves with age.",
        category: "men's clothing",
        image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80", // Replaced
        rating: { rate: 4.7, count: 250 },
        brand: "DenimCo",
    },
    {
        id: 7,
        title: "Essential Cotton T-Shirt",
        price: 35.00,
        description: "100% organic cotton. The perfect fit for everyday comfort.",
        category: "men's clothing",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.3, count: 320 },
        brand: "Basics",
    },
    {
        id: 8,
        title: "Oxford Button-Down Shirt",
        price: 59.99,
        description: "Crisp, tailored fit perfect for the office or casual weekends.",
        category: "men's clothing",
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.5, count: 180 },
        brand: "Oxford",
    },
    {
        id: 9,
        title: "Slim Fit Chino Pants",
        price: 49.50,
        description: "Modern slim fit chinos with stretch for all-day comfort.",
        category: "men's clothing",
        image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80", // Replaced
        rating: { rate: 4.4, count: 150 },
        brand: "UrbanFlex",
    },

    // Women's Clothing
    {
        id: 10,
        title: "Floral Summer Dress",
        price: 79.00,
        description: "Lightweight and breezy floral dress, perfect for warm weather.",
        category: "women's clothing",
        image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=600&q=80", // Replaced
        rating: { rate: 4.8, count: 410 },
        brand: "Bloom",
    },
    {
        id: 11,
        title: "Oversized Knit Sweater",
        price: 65.00,
        description: "Cozy oversized knit sweater for chilly days.",
        category: "women's clothing",
        image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.6, count: 290 },
        brand: "CozyKnit",
    },
    {
        id: 12,
        title: "High-Waist Skinny Jeans",
        price: 55.00,
        description: "Flattering high-waist fit with premium stretch denim.",
        category: "women's clothing",
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.5, count: 330 },
        brand: "DenimCo",
    },

    // Jewelery
    {
        id: 13,
        title: "Gold Plated Layered Necklace",
        price: 45.00,
        description: "Delicate layered necklace with 18k gold plating.",
        category: "jewelery",
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80", // Replaced
        rating: { rate: 4.7, count: 120 },
        brand: "LuxeGem",
    },
    {
        id: 14,
        title: "Sterling Silver Hoop Earrings",
        price: 35.00,
        description: "Classic minimalist hoop earrings made from sterling silver.",
        category: "jewelery",
        image: "https://images.unsplash.com/photo-1629224316810-9d8805b95076?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.6, count: 95 },
        brand: "Argento",
    },
    {
        id: 15,
        title: "Crystal Solitaire Ring",
        price: 89.00,
        description: "Elegant solitaire crystal ring, perfect for special occasions.",
        category: "jewelery",
        image: "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.8, count: 60 },
        brand: "LuxeGem",
    },

    // Fashion (Accessories)
    {
        id: 16,
        title: "Premium Urban Backpack",
        price: 129.99,
        description: "Sleek, durable, and ready for the city. Features a padded laptop compartment.",
        category: "fashion",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.8, count: 210 },
        brand: "Nordic Gear",
    },
    {
        id: 17,
        title: "Minimalist Leather Watch",
        price: 199.50,
        description: "Elegant timezone tracking with a genuine leather strap.",
        category: "fashion",
        image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.6, count: 145 },
        brand: "Chrono",
    },
    {
        id: 18,
        title: "Classic Aviator Sunglasses",
        price: 140.00,
        description: "Timeless aviator style with polarized lenses.",
        category: "fashion",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.7, count: 200 },
        brand: "SunRay",
    },

    // Home
    {
        id: 19,
        title: "Minimalist Desk Lamp",
        price: 65.00,
        description: "Adjustable LED brightness and color temperature. Modern matte finish.",
        category: "home",
        image: "https://images.unsplash.com/photo-1513506003013-953a45bf4811?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.4, count: 150 },
        brand: "Lumina",
    },
    {
        id: 20,
        title: "Ceramic Plant Pot Set",
        price: 45.00,
        description: "Set of 3 minimalist ceramic planters for indoor greenery.",
        category: "home",
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.9, count: 310 },
        brand: "GreenSpace",
    },
    {
        id: 21,
        title: "Soft Knit Throw Blanket",
        price: 85.00,
        description: "Luxuriously soft oversized knit blanket for cozy evenings.",
        category: "home",
        image: "https://images.unsplash.com/photo-1507764923504-cd90bf7da772?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.8, count: 275 },
        brand: "ComfyHome",
    },
    {
        id: 22,
        title: "Eco-Friendly Water Bottle",
        price: 45.00,
        description: "Double-walled vacuum insulation keeps drinks cold for 24 hours.",
        category: "home",
        image: "https://images.unsplash.com/photo-1564466013110-a4ea243c3d52?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.8, count: 400 },
        brand: "PureLife",
    },

    // Sport
    {
        id: 23,
        title: "Running Performance Sneakers",
        price: 140.00,
        description: "Lightweight, breathable mesh with responsive cushioning.",
        category: "sport",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.6, count: 320 },
        brand: "Velocity",
    },
    {
        id: 24,
        title: "Yoga Mat Pro",
        price: 60.00,
        description: "Non-slip surface with perfect cushioning for yoga and pilates.",
        category: "sport",
        image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&q=80", // Replaced
        rating: { rate: 4.7, count: 230 },
        brand: "ZenFlex",
    },
    {
        id: 25,
        title: "Adjustable Dumbbell Set",
        price: 199.00,
        description: "Space-saving adjustable dumbbells for versatile home workouts.",
        category: "sport",
        image: "https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.8, count: 150 },
        brand: "PowerLift",
    },
];

// Re-replace broken Water Bottle Image
products[21].image = "https://images.unsplash.com/photo-1523351191164-897b2d561571?auto=format&fit=crop&w=600&q=80"; // Replaced 22 (index 21?) Wait, IDs are 1-based, array is 0-based.
// Image for ID 22 (Water Bottle):
products[21] = {
    id: 22,
    title: "Eco-Friendly Water Bottle",
    price: 45.00,
    description: "Double-walled vacuum insulation keeps drinks cold for 24 hours.",
    category: "home",
    image: "https://images.unsplash.com/photo-1523351191164-897b2d561571?auto=format&fit=crop&w=600&q=80",
    rating: { rate: 4.8, count: 400 },
    brand: "PureLife",
};
