import { Product } from "@/types/product";

export const products: Product[] = [
    {
        id: 1,
        title: "Premium Urban Backpack",
        price: 129.99,
        description: "Sleek, durable, and ready for the city. Features a padded laptop compartment and water-resistant materials.",
        category: "fashion",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.8, count: 210 },
        brand: "Nordic Gear",
    },
    {
        id: 2,
        title: "Minimalist Leather Watch",
        price: 199.50,
        description: "Elegant timezone tracking with a genuine leather strap and sapphire crystal glass.",
        category: "accessories",
        image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.6, count: 145 },
        brand: "Chrono",
    },
    {
        id: 3,
        title: "Wireless Noise-Canceling Headphones",
        price: 299.99,
        description: "Immersive sound with industry-leading noise cancellation. 30-hour battery life.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.9, count: 530 },
        brand: "AudioPro",
    },
    {
        id: 4,
        title: "Essential Cotton T-Shirt",
        price: 35.00,
        description: "100% organic cotton. The perfect fit for everyday comfort.",
        category: "fashion",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.3, count: 320 },
        brand: "Basics",
    },
    {
        id: 5,
        title: "Smart Home Speaker",
        price: 89.99,
        description: "Voice-controlled assistant with room-filling sound and smart home integration.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1589492477829-5e65395b66cc?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.5, count: 180 },
        brand: "TechHome",
    },
    {
        id: 6,
        title: "Classic Denim Jacket",
        price: 110.00,
        description: "Vintage wash denim jacket. Timeless style that improves with age.",
        category: "fashion",
        image: "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.7, count: 250 },
        brand: "DenimCo",
    },
    {
        id: 7,
        title: "Eco-Friendly Water Bottle",
        price: 45.00,
        description: "Double-walled vacuum insulation keeps drinks cold for 24 hours. BPA-free.",
        category: "lifestyle",
        image: "https://images.unsplash.com/photo-1602143407151-01114195bc51?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.8, count: 400 },
        brand: "PureLife",
    },
    {
        id: 8,
        title: "Professional Mechanical Keyboard",
        price: 159.00,
        description: "Tactile mechanical switches for ultimate typing precision and speed.",
        category: "electronics",
        image: "https://images.unsplash.com/photo-1587829741301-dc798b91a05c?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.9, count: 600 },
        brand: "KeyMaster",
    },
    {
        id: 9,
        title: "Running Performance Sneakers",
        price: 140.00,
        description: "Lightweight, breathable mesh with responsive cushioning for long-distance runs.",
        category: "sport",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.6, count: 320 },
        brand: "Velocity",
    },
    {
        id: 10,
        title: "Minimalist Desk Lamp",
        price: 65.00,
        description: "Adjustable LED brightness and color temperature. Modern matte finish.",
        category: "home",
        image: "https://images.unsplash.com/photo-1534073828943-f801091a7d58?auto=format&fit=crop&w=600&q=80",
        rating: { rate: 4.4, count: 150 },
        brand: "Lumina",
    },
];
